# Generated by Django 3.0.3 on 2020-04-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='titmestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='titmestamp',
            new_name='timestamp',
        ),
    ]
